### ISSUE TITLE
Sending and receiving complex objects

### ISSUE THREAD

**Issue by andrund** [dajuric/websocket-rpc#2]
When a client receives a complex object from the server, the properties of the complex object are all null. Any idea why? Sending plain strings works fine.

var responses = await RPC.For<Interface>().CallAsync(x => x.LoadPlayer(1234))
var response = responses.First();
response.PlayerName == null?????

**Comment by dajuric** [comment]
Hi Anders,

   that should not be the case. It would be great if you could send me the
bare-bone code so I can check what is happening ?
  Thanks.

Best,
Darko

2018-02-02 14:24 GMT+01:00 Anders R <notifications@github.com>:

**Comment by andrund** [comment]
Hi There,
I solved it by converting the request and response objects as json and then send it as a string just for now. I will make a small code demo of the issue during the weekend. 

Nice work with the websocket-rpc libs by the way. I just tried to use it in Unity and worked like a charm! 

One thing I don't understand (but it's really not a problem) is why CallAsync returns a collection and not just a single object. 

Anders

**Comment by dajuric** [comment]
Hi Anders,

I am really sorry, that should have worked flawlessly. I am sending you an sample which uses complex structures. 

-------------------
The reason why the the 'CallAsync' returns a collection is because it executes RPC on multiple clients and every item in the collection is the result for a single client. 

E.g. :
`var results = await RPC.For<MyAPI>().CallAsync(x => x.GetId())` will invoke 'GetId' on all clients which are associated with the 'MyAPI' class (**mesage broadcast**), but the following statement

`var results = await RPC.For<MyAPI>(this).CallAsync(x => x.GetId());`, where 'this' is the instance of the 'MyAPI' class will call 'GetId' only on the client which is associated with that object (**direct messaging**), and will return only one result, so you can use var `result = results.First()`.

I hope that helps.

--------------------------
Thanks for the nice comment. I appreciate it.
If you like the library, it would be great if you could star the repository or/and the [CodeProject ](https://www.codeproject.com/Articles/1210957/Introducing-Lightweight-WebSocket-RPC-Library-for) article. That would impact on my encouragement to further develop the library.

Best,
Darko

[ComplexObjectSample.zip](https://github.com/dajuric/websocket-rpc/files/1692339/ComplexObjectSample.zip)

**Comment by andrund** [comment]
Hi Dajuric
Text and code sample updated...
Thanks for the sample. I've tried it and seems to work, but our cases are a bit different. I'm using a .NET core client. 

My issues right now are:

1 
When a .NET Core client sends a request to server and server responds with a complex object, the properties in the response object are not set. If Server pushes a complex object, then the properties are set. Only Request/Response is currently not working.

2 
When client calls server, the event handler OnReceive is called on both client and server (Only Server sounds right to me)
When server calls a client, the event handler OnReceive is called on both client and server (Only Client sounds right to me)
When server push a message to clients OnReceive is called on both client and server (Only Client sounds right to me)

3 
When client calls a method on server, how do I get the client connection and WebSocketContext for that specific client from the server method?

4
Attached code sample contains simple logic for grouping connections (game rooms etc. I know the logic doesn't scale on mulitple servers). Any additional comments on how to accomplish that?

Check new provided sample SocketTest2.zip
[SocketTest2.zip](https://github.com/dajuric/websocket-rpc/files/1699261/SocketTest2.zip)

Thanks a lot

**Comment by dajuric** [comment]
Hi Anders,

## The First Version

 I have tested your code and have noticed that:
-  complex object receive/send works fine (removed the project, put NuGet package instead)
-  the update function does not work because async is missing, you have to await the Task not return the Task. In addition there were not any connections in the collection '_groups'. 
- a single Server object has been used. This pattern prevents you from distinguishing a single client (you can not filter a single client).  
-----------------------------
This library encourages you to work with the objects rather the connections. I have made a sample for you which does the same. It assumes that a player can belong only to a single group and that communication should be between a server-game and a player-pool.

Let me know what you think.
[WebGame-withInheritGrouping.zip](https://github.com/dajuric/websocket-rpc/files/1701090/WebGame.zip)


## The Second Version

1.  It works. I have attached the sample for .NET Core server and client.
[ComplexObjectTest-dotNET.zip](https://github.com/dajuric/websocket-rpc/files/1701355/ComplexObjectTest-dotNET.zip)

2.  Imagine you are calling `int GetMyAge(string id)` from the server. First the client's OnReceive is triggered because args and the function name are transmitted and then the server's OnReceive is triggered for the result message. Is you do not want to receive such messages check `RPC.IsRpcMessage`. Using this you can discard such messages.

3. Check the sample I have enclosed. In short the result from RPC.For(...) returns a collection of binders which have the Connection property: `RPC.For<IMyClass>().Select(x => x.Connection)`.

4. You can try Azure Service Fabric where you would have multiple server instances and the websokcet connections are automatically balanced. To "talk" across instances you can use ServiceFabric API or you can make an aggregator service. The internal aggregator service would have websokcet server listener which would receive connections from the server instances (services). Therefore, each server would have to have an additional websocket client. 

------------------------------
I have made a second version of WebGame which supports direct communication between the client's player and the server's subscription. Grouping the player subscriptions is really simple as shown in the enclosed sample.
[WebGame-2.zip](https://github.com/dajuric/websocket-rpc/files/1701377/WebGame-2.zip)

P.S.
  my name is Darko, 'dajuric' is the username

Best,
Darko

**Comment by andrund** [comment]
Hi Darko,
Thanks a lot for the new code sample. It works like a charm! Now I understand how things work and I really like your approach. Wonderful.

One small code change that was necessary and I'm sure that is just a typo
//var rBinders = Subscriptions.SelectMany(x => RPC.For<IPlayer>(x));
var rBinders = gamePlayers.SelectMany(x => RPC.For<IPlayer>(x));

Will let you know about my progress

Have a good day!

**Comment by dajuric** [comment]
I am glad you like it.
And have a nice day too.
